# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту sergey.se1ove.morozov@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - morozov.java.job@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
    global:
      - CODECOV_TOKEN="b1624dd2-6e37-427e-a525-9d5001bf4bad"